# common configuration
spring:
    application:
        name: springboot-init
    # default active
    profiles:
        active: dev
    # swagger3 supporting
    mvc:
        pathmatch:
            matching-strategy: ant_path_matcher
    # session configuration
    session:
        # todo uncomment 'store-type' to enable distributed session(Must configure redis in advance)
        # store-type: redis
        # 30 days
        timeout: 2592000
    # Database configuration
    # todo modify to your own
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/my_db?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8&useSSL=false
        username: root
        password: root
    # Redis configuration
    # todo uncomment and modify to your own
    #  redis:
    #    database: 1
    #    host: localhost
    #    port: 6379
    #    timeout: 5000
    #    password: 123456
    # Elasticsearch configuration
    # todo uncomment and modify to your own
    #  elasticsearch:
    #    uris: http://localhost:9200
    #    username: root
    #    password: 123456
    # File upload
    servlet:
        multipart:
            max-file-size: 10MB
server:
    address: 0.0.0.0
    port: 8101
    servlet:
        context-path: /api
        # 30 days
        session:
            cookie:
                max-age: 2592000
mybatis-plus:
    configuration:
        map-underscore-to-camel-case: false
        log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    global-config:
        db-config:
            logic-delete-field: isDelete
            logic-delete-value: 1
            logic-not-delete-value: 0
# Wechat related
wx:
    # Official Account Platform
    # todo Modify to your own
    mp:
        token: xxx
        aesKey: xxx
        appId: xxx
        secret: xxx
        config-storage:
            http-client-type: HttpClient
            key-prefix: wx
            redis:
                host: 127.0.0.1
                port: 6379
            type: Memory
    # Open platform
    # todo Modify to your own
    open:
        appId: xxx
        appSecret: xxx
# Object Storage
# todo Modify to your own
cos:
    client:
        accessKey: xxx
        secretKey: xxx
        region: xxx
        bucket: xxx
# API documentation configuration
knife4j:
    enable: true
    openapi:
        title: "API Documentation"
        version: 1.0
        group:
            default:
                api-rule: package
                api-rule-resources:
                    - top.wayne06.generalbackend.controller
